admin/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end
  get "user/edit_pwd/:id" ,to: "users#edit_pwd", as: "edit_user_pwd"
  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]


end

admin/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

admin/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

admin/app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

admin/app/models/course_progress.rb
class CourseProgress < ApplicationRecord
end

admin/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :section
  has_many :answers
  has_many :pics
end

admin/app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

admin/app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

admin/app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :screencast
  has_many :options
  has_many :imgs
end

admin/app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

admin/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

admin/app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

admin/app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses
  has_many :courseProgresses, :dependent => :destroy
end

admin/app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

admin/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subject.lang=0
    @subject.no = Subject.maximum(:no) ? Subject.maximum(:no)+1 : 1
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:no,:lang,:name, :description, :logo)
    end
end

admin/app/helpers/application_helper.rb
module ApplicationHelper
end

admin/app/helpers/courses_helper.rb
module CoursesHelper
end

admin/app/helpers/options_helper.rb
module OptionsHelper
end

admin/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

admin/app/helpers/subjects_helper.rb
module SubjectsHelper
end

admin/app/helpers/users_helper.rb
module UsersHelper
end

admin/app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :no %>
    <%= form.text_field :no, id: :subject_no, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :lang,"Language (0-kg,1-ru)" %>
    <%= form.text_field :lang, id: :subject_lang, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :subject_description , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :subject_logo , class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-primary" %>
<%= link_to 'Back', subjects_path,class:"btn btn-outline-primary" %>
  </div>
<% end %>

admin/app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

admin/app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table class="table">
  <thead>
    <tr>
      <th>No</th>
      <th>Logo</th>
      <th>Name</th>
      <th>Lang</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.no %></td>
        <td><%= image_tag subject.logo.url(:thumb) %></td>
        <td><%= subject.name %></td>
        <td><%= subject.lang %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

admin/app/views/subjects/new.html.erb
<h1>New Subject</h1>
<%= render 'form', subject: @subject %>

admin/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    SUBJECT
  </div>
  <div class="card-body">
    <%= image_tag @subject.logo.url(:medium), class:"rounded float-left mr-3" %>
    <h5 class="card-title"><%= @subject.no %>.<%= @subject.name %></h5>
    <p class="card-text"><%= @subject.lang %></p>
    <p class="card-text"><%= @subject.description %></p>
    <div class="clearfix">
      <%= link_to 'Edit SUBJECT', edit_subject_path(@subject), class:"btn btn-outline-primary"%> 
      <%= link_to 'Back TO LIST', subjects_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header">
    COURSES OF <%=@subject.name%> 
  </div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>No</th>
          <th>Name</th>
          <th>Description</th>
          <th>Logo</th>
          <th>Level</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @subject.courses.each do |course| %>
          <tr>
            <td><%= course.no %></td>
            <td><%= course.name %></td>
            <td><%= course.description %></td>
            <td><%= image_tag course.logo.url(:thumb) %></td>
            <td><%= course.level %></td>
            <td><%= link_to 'Show', course %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', [@subject,course], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= link_to 'New Course', new_subject_course_path(@subject),class:"btn btn-outline-secondary" %>
  </div>
</div>
<br>