admin/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end
  get "user/edit_pwd/:id" ,to: "users#edit_pwd", as: "edit_user_pwd"
  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]


end

admin/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

admin/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

admin/app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

admin/app/models/course_progress.rb
class CourseProgress < ApplicationRecord
end

admin/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :section
  has_many :answers
  has_many :pics
end

admin/app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

admin/app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

admin/app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :screencast
  has_many :options
  has_many :imgs
end

admin/app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

admin/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

admin/app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

admin/app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses
  has_many :courseProgresses, :dependent => :destroy
end

admin/app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

admin/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_subject, only: [:index,:new, :create, :destroy]

  def index
    @courses = @subject.courses
  end

  def show
    @lectors = Lector.all
  end

  def new
    @course = @subject.courses.new
    @course.no = @subject.courses.maximum(:no) ? @subject.courses.maximum(:no)+1 : 1
  end

  def edit
  end

  def create
    @course = @subject.courses.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def add_lector 
    course = Course.find(params[:course_id])
    lector = Lector.find(params[:lector_id])
    course.lectors<<lector
    course.save
    respond_to do |format|
      format.html { redirect_to course }
    end
  end
  def remove_lector 
    course = Course.find(params[:course_id])
    lector = Lector.find(params[:lector_id])
    course.lectors.destroy(params[:lector_id])
    course.save
    respond_to do |format|
      format.html { redirect_to course }
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to @subject, notice: 'Course was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    def set_subject
      @subject = Subject.find(params[:subject_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:no, :name, :description, :logo, :subject_id, :level, :lector)
    end
end

admin/app/helpers/courses_helper.rb
module CoursesHelper
end

admin/app/helpers/options_helper.rb
module OptionsHelper
end

admin/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

admin/app/helpers/subjects_helper.rb
module SubjectsHelper
end

admin/app/helpers/users_helper.rb
module UsersHelper
end

admin/app/views/courses/_form.html.erb
<%= form_with(model: [subject,course], local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :no %>
    <%= form.text_field :no, id: :course_no , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :course_description , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :course_logo , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :level %>
    <%= form.number_field :level, id: :course_level , class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-primary" %>
<%= link_to 'Back',subject||course,class:"btn btn-outline-primary" %>
  </div>
<% end %>

admin/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', subject: @subject,course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', @course.subject %>

admin/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', {subject:@subject, course: @course} %>

<%= link_to 'Back', @subject %>

admin/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    COURSE OF <%=link_to @course.subject.name,@course.subject %>
</div>
<div class="card-body">
  <%= image_tag @course.logo.url(:medium), class:"rounded float-left mr-3" %>
  <h5 class="card-title"><%= @course.no %>. <%= @course.name %></h5>
  <p class="card-text"><%= @course.description %></p>
  <p><strong>Level:</strong><%= @course.level %></p>
  <div class="clearfix">
    <%= link_to 'Edit COURSE', edit_course_path(@course), class:"btn btn-outline-primary"%> 
    <%= link_to 'Back TO SUBJECT', @course.subject, class:"btn btn-outline-primary" %>
  </div>
</div>
</div>
<br/>

<div class="card">
  <div class="card-header"> LECTORS OF <%=@course.name%>i</div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Fullname</th>
          <th>Level</th>
          <th>Degree</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @course.lectors.each do |lector| %>
          <tr>
            <td><%= image_tag lector.photo.url(:thumb) %></td>
            <td><%= lector.fullname %></td>
            <td><%= lector.level %></td>
            <td><%= lector.degree %></td>
            <td><%= link_to 'Destroy', remove_lector_path(@course.id,lector.id), data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
    <a class="btn btn-outline-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Add lector
    </a>
    </p>
    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <table class="table">
          <thead>
            <tr>
              <th>Fullname</th>
              <th>Level</th>
              <th>Degree</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @lectors.each do |lector| %>
              <tr>
                <td><%= image_tag lector.photo.url(:thumb) %></td>
                <td><%= lector.fullname %></td>
                <td><%= lector.level %></td>
                <td><%= lector.degree %></td>
                <td><%= link_to 'Select', add_lector_path(@course.id, lector.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-header"> SECTIONS OF <%=@course.name%>i</div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>No</th>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @course.sections.each do |section| %>
          <tr>
            <td><%= section.no %></td>
            <td><%= section.name %></td>
            <td><%= section.description%></td>
            <td><%= link_to 'Show', section %></td>
            <td><%= link_to 'Edit', edit_section_path(section) %></td>
            <td><%= link_to 'Destroy', [@course,section], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New section', new_course_section_path(@course),class:"btn btn-outline-secondary" %>
  </div>
</div>

<br>