admin/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end
  get "user/edit_pwd/:id" ,to: "users#edit_pwd", as: "edit_user_pwd"
  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]


end

admin/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

admin/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

admin/app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

admin/app/models/course_progress.rb
class CourseProgress < ApplicationRecord
end

admin/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :section
  has_many :answers
  has_many :pics
end

admin/app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

admin/app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

admin/app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :screencast
  has_many :options
  has_many :imgs
end

admin/app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

admin/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

admin/app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

admin/app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses
  has_many :courseProgresses, :dependent => :destroy
end

admin/app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

admin/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :set_section, only: [:index,:new, :create, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = @section.exams
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = @section.exams.new
    @exam.no = @section.exams.maximum(:no)
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = @section.exams.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to @section, notice: 'Exam was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end
    def set_section
      @section = Section.find(params[:section_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:no, :section_id, :question, :details, :score)
    end
end

admin/app/helpers/courses_helper.rb
module CoursesHelper
end

admin/app/helpers/options_helper.rb
module OptionsHelper
end

admin/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

admin/app/helpers/subjects_helper.rb
module SubjectsHelper
end

admin/app/helpers/users_helper.rb
module UsersHelper
end

admin/app/views/exams/_form.html.erb
<%= form_with(model: [section,exam], local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :no %>
    <%= form.text_field :no, id: :exam_no , class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :question %>
    <%= form.text_field :question, id: :exam_question , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :details %>
    <%= form.text_field :details, id: :exam_details, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :score %>
    <%= form.number_field :score, id: :exam_score, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit  class:"btn btn-outline-primary" %>
<%= link_to 'Back',section||exam,class:"btn btn-outline-primary" %>
  </div>
<% end %>

admin/app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', section: @section,exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', @exam.section%>

admin/app/views/exams/new.html.erb
<h1>New Question</h1>

<%= render 'form', {section: @section, exam: @exam} %>

admin/app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">QUESTIONS FOR 
    <%= link_to @exam.section.name, @exam.section%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @exam.no%>. <%= @exam.question%></h5>
    <p><strong>Details:</strong><%= @exam.details %></p>
    <p><strong>Score:</strong> <%= @exam.score %></p>
    <div class="clearfix">
      <%= link_to 'Edit EXAM Question', edit_exam_path(@exam), class:"btn btn-outline-primary"%> 
      <%= link_to 'Back to SECTION', @exam.section, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header">OPTIONS FOR <%=@exam.question%></div>

  <div class="card-body">
    <table class="table">

      <thead>
        <tr>
          <th>Correct</th>
          <th>Value</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @exam.answers.each do |answer| %>
          <tr>
            <td><%= answer.correct %></td>
            <td><%= answer.value %></td>
            <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
            <td><%= link_to 'Destroy', [answer.exam,answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Option', new_exam_answer_path(@exam), class:"btn btn-outline-secondary" %>
  </div>
</div>
<div class="card">
  <div class="card-header">PICS OF <%=@exam.question%></div>

  <div class="card-body">
    <table class="table">

      <thead>
        <tr>
          <th>Title</th>
          <th>Image</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @exam.pics.each do |pic| %>
          <tr>
            <td><%= pic.title %></td>
            <td><%= image_tag pic.img.url(:thumb) %></td>
            <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
            <td><%= link_to 'Destroy', [pic.exam,pic], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Image', new_exam_pic_path(@exam), class:"btn btn-outline-secondary" %>
  </div>
</div>