admin/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end
  get "user/edit_pwd/:id" ,to: "users#edit_pwd", as: "edit_user_pwd"
  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]


end

admin/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

admin/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

admin/app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

admin/app/models/course_progress.rb
class CourseProgress < ApplicationRecord
end

admin/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :section
  has_many :answers
  has_many :pics
end

admin/app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

admin/app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

admin/app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

admin/app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :screencast
  has_many :options
  has_many :imgs
end

admin/app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

admin/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

admin/app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

admin/app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses
  has_many :courseProgresses, :dependent => :destroy
end

admin/app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

admin/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit,:edit_pwd, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @edit_password = true 
  end

  # GET /users/1/edit
  def edit
    @edit_password = false 
  end
  def edit_pwd
    @edit_password = true
    render :edit
  end 

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]

    respond_to do |format|
      @user.email.downcase!
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        if user_params[:password]
          @user.password = user_params[:password]
          @user.save
        end
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fullname,:username, :email, :phone, :password, :lang)
    end
    def user_params_update
      params.require(:user).permit(:fullname,:username, :email, :phone, :lang)
    end
end

admin/app/helpers/application_helper.rb
module ApplicationHelper
end

admin/app/helpers/courses_helper.rb
module CoursesHelper
end

admin/app/helpers/options_helper.rb
module OptionsHelper
end

admin/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

admin/app/helpers/subjects_helper.rb
module SubjectsHelper
end

admin/app/helpers/users_helper.rb
module UsersHelper
end

admin/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if !@edit_password %>
    <div class="field form-group">
      <%= form.label :username %>
      <%= form.text_field :username, id: :user_username, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :fullname %>
      <%= form.text_field :fullname, id: :user_fullname, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :phone %>
      <%= form.text_field :phone, id: :user_phone, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :lang %>
      <%= form.text_field :lang, id: :user_lang, class:"form-control" %>
    </div>
  <% end %>
  <% if @edit_password %>
    <div class="field form-group">
      <%= form.label :password %>
      <%= form.text_field :password, id: :user_password, class:"form-control" %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-primary" %>
<%= link_to 'Back', @user||users_path,class:"btn btn-outline-primary"  %>
  </div>
<% end %>

admin/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

admin/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Fullname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Lang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.fullname %></td>
        <td><%= user.email %></td>
        <td><%= user.phone%></td>
        <td><%= user.lang %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

admin/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

admin/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
   User 
  </div>
  <div class="card-body">
    <h5 class="card-title">fullname: <%= @user.fullname %></h5>
    <p class="card-text">username: <%= @user.username %></p>
    <p class="card-text">email: <%= @user.email %></p>
    <p class="card-text">phone: <%= @user.phone %></p>
    <p class="card-text">lang: <%= @user.lang %></p>
    <div class="clearfix">
      <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-outline-primary" %> 
      <%= link_to 'Change password', edit_user_pwd_path(@user), class:"btn btn-outline-primary" %> 
      <%= link_to 'Back', users_path , class:"btn btn-outline-primary"%>
    </div>
  </div>
</div>
<br/>
<div class="card">
  <div class="card-header">
    COURSES OF <%=@user.fullname%> 
  </div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Logo</th>
          <th>Level</th>
          <th>Lector</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.userCourses.each do |userCourse| %>
          <tr>
            <td><%= userCourse.course.name %></td>
            <td><%= userCourse.course.description %></td>
            <td><%= image_tag userCourse.course.logo.url(:thumb) %></td>
            <td><%= userCourse.course.level %></td>
            <td><%= userCourse.course.lector %></td>
            <td><%= link_to 'Edit', edit_user_course_path(userCourse) %></td>
            <td><%= link_to 'Destroy', [@user,userCourse], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= link_to 'Add Course', new_user_user_course_path(@user),class:"btn btn-outline-secondary" %>
  </div>
</div>